{
 "title": "LODA",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Generated",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "-g $tag_generator_version -p $tag_num_operations -n $tag_max_constant -a $tag_operand_types -o $tag_operation_types  -e $tag_program_template",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "num_operations" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "generated",
     "query": "SELECT mean(\"value\") FROM \"loda_programs\" WHERE $timeFilter AND \"type\"='generated' GROUP BY time($__interval), \"generator_version\", \"num_operations\", \"max_constant\", \"operation_types\", \"operand_types\", \"program_template\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "New",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "-g $tag_generator_version -p $tag_num_operations -n $tag_max_constant -a $tag_operand_types -o $tag_operation_types  -e $tag_program_template",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"loda_programs\" WHERE $timeFilter AND \"type\"='new' GROUP BY time($__interval), \"generator_version\", \"num_operations\", \"max_constant\", \"operation_types\", \"operand_types\", \"program_template\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Updated",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "-g $tag_generator_version -p $tag_num_operations -n $tag_max_constant -a $tag_operand_types -o $tag_operation_types  -e $tag_program_template",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"loda_programs\" WHERE $timeFilter AND \"type\"='updated' GROUP BY time($__interval), \"generator_version\", \"num_operations\", \"max_constant\", \"operation_types\", \"operand_types\", \"program_template\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Candidates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_matcher",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"loda_matches\" WHERE \"type\"='candidate' AND $timeFilter GROUP BY time($__interval), \"matcher\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Successes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_matcher",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"loda_matches\" WHERE \"type\"='success' AND $timeFilter GROUP BY time($__interval), \"matcher\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "False Positives",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_matcher",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"loda_matches\" WHERE \"type\"='false_positive' AND $timeFilter GROUP BY time($__interval), \"matcher\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_matcher",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"loda_matches\" WHERE \"type\"='error' AND $timeFilter GROUP BY time($__interval), \"matcher\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}